site_name: Suppgram Documentation
site_url: https://suppgram.readthedocs.io/
repo_name: GitHub
repo_url: https://github.com/Saluev/suppgram/
site_description: Simple Telegram-based support system written in Python
nav:
  - Home: index.md
  - Usage:
      - Quickstart: usage/quickstart.md
      - 'All-in-one CLI': usage/all_in_one_cli.md
      - Builder: usage/builder.md
      - Updating to a newer version: usage/updating.md
  - Features:
      - 'PostgreSQL/SQLite integration': features/sql_integration.md
      - 'MongoDB integration': features/mongodb_integration.md
      - 'Telegram integration': features/telegram_integration.md
      - 'PubNub integration': features/pubnub_integration.md
      - 'Customizing texts': features/customizing_texts.md
  - Development:
      - 'Contribution guide': development/contribution_guide.md
      - 'Architecture overview': development/architecture_overview.md
      - 'Core entities': development/core_entities.md
      - 'Customer frontends': development/customer_frontends.md
      - 'Agent frontend': development/agent_frontends.md
      - 'Manager frontend': development/manager_frontends.md
      - 'Backend': development/backends.md
      - 'Storages': development/storages.md
      - 'Bridges': development/bridges.md
theme: readthedocs
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
