"""Support images

Revision ID: fd93d2874998
Revises: 48f9a7635310
Create Date: 2025-03-08 13:42:12.967329

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd93d2874998"
down_revision = "48f9a7635310"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "suppgram_conversation_messages", sa.Column("image_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("suppgram_conversation_messages", "image_url")
    # ### end Alembic commands ###
